# Generated by Django 3.2.6 on 2021-10-31 22:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filekeep', models.FileField(blank=True, null=True, upload_to=api.models.upload_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
