# Generated by Django 3.2.6 on 2021-11-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211101_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billerservicesuploads',
            name='file_collection',
        ),
        migrations.RemoveField(
            model_name='billerservicesuploads',
            name='file_signatories',
        ),
    ]
